#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
 
coolify = { 
} 
agent.write_envfile("coolify.env", coolify) 
 
postgres = { 
} 
agent.write_envfile("postgres.env", postgres) 
 
redis = { 
} 
agent.write_envfile("redis.env", redis) 
 
soketi = { 
} 
agent.write_envfile("soketi.env", soketi) 
