#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

# # Dump the configuration to stdout
# # json.dump(config, fp=sys.stdout)
# if os.path.exists("coolify.env"): 
# 	data = agent.read_envfile("coolify.env") 
#  
# if os.path.exists("postgres.env"): 
# 	data = agent.read_envfile("postgres.env") 
#  
# if os.path.exists("redis.env"): 
# 	data = agent.read_envfile("redis.env") 
#  
# if os.path.exists("soketi.env"): 
# 	data = agent.read_envfile("soketi.env") 
 
json.dump(config, fp=sys.stdout)
